doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        driver:   '%env(DB_DRIVER)%'
        host:     '%env(DB_HOST)%'
        port:     '%env(DB_PORT)%'
        dbname:   '%env(DB_NAME)%'
        user:     '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        charset:  '%env(DB_CHARSET)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: "%env(DB_VERSION)%"
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
